### ISSUE TITLE
help to understand error in logs

### ISSUE THREAD

**Issue by pilot1981** [danimtb/dasshio#102]
Hi,
I configured dasshio add-on and log are ok:

timeout: 20
buttons:
  - name: test
    address: '6C:xxxxxxxx:49:CC'
    domain: light
    service: toggle
    service_data: '{\"entity_id\": \"light.hue_color_lamp_1\"}'

 but when I click on my Amazon dash button nothing happen (power on a light) and I found these errors in logs:

File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-30 19:06:14,347 | INFO | Finishing sniffing
2020-12-30 19:06:14,349 | INFO | Packet captured! Waiting 20 seconds...
2020-12-30 19:06:34,364 | INFO | Starting sniffing...
2020-12-30 19:06:59,164 | INFO | test button pressed!
2020-12-30 19:06:59,166 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-30 19:06:59,226 | INFO | Finishing sniffing
2020-12-30 19:06:59,228 | INFO | Packet captured! Waiting 20 seconds...
2020-12-30 19:07:19,248 | INFO | Starting sniffing...
2020-12-30 19:14:47,448 | INFO | test button pressed!
2020-12-30 19:14:47,451 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-30 19:14:47,527 | INFO | Finishing sniffing
2020-12-30 19:14:47,528 | INFO | Packet captured! Waiting 20 seconds...
2020-12-30 19:15:07,541 | INFO | Starting sniffing...
2020-12-30 19:31:35,179 | INFO | test button pressed!
2020-12-30 19:31:35,180 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-30 19:31:35,246 | INFO | Finishing sniffing
2020-12-30 19:31:35,248 | INFO | Packet captured! Waiting 20 seconds...
2020-12-30 19:31:55,270 | INFO | Starting sniffing...
2020-12-30 19:31:57,696 | INFO | test button pressed!
2020-12-30 19:31:57,698 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-30 19:31:57,766 | INFO | Finishing sniffing
2020-12-30 19:31:57,767 | INFO | Packet captured! Waiting 20 seconds...
2020-12-30 19:32:17,771 | INFO | Starting sniffing...
2020-12-30 19:40:21,845 | INFO | test button pressed!
2020-12-30 19:40:21,848 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-30 19:40:21,906 | INFO | Finishing sniffing
2020-12-30 19:40:21,907 | INFO | Packet captured! Waiting 20 seconds...
2020-12-30 19:40:41,926 | INFO | Starting sniffing...
2020-12-30 20:15:01,052 | INFO | test button pressed!
2020-12-30 20:15:01,054 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-30 20:15:01,137 | INFO | Finishing sniffing
2020-12-30 20:15:01,140 | INFO | Packet captured! Waiting 20 seconds...
2020-12-30 20:15:21,148 | INFO | Starting sniffing...

**Comment by pilot1981** [comment]
I solved problem of name but now I found these errors:

2020-12-31 14:00:43,871 | INFO | test button pressed!
2020-12-31 14:00:43,873 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-31 14:00:43,947 | INFO | Finishing sniffing
2020-12-31 14:00:43,948 | INFO | Packet captured! Waiting 20 seconds...
2020-12-31 14:01:03,966 | INFO | Starting sniffing...
2020-12-31 14:01:09,360 | INFO | test button pressed!
2020-12-31 14:01:09,363 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/dasshio.py", line 63, in arp_display
    json=json.loads(button["service_data"]),
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
2020-12-31 14:01:09,436 | INFO | Finishing sniffing
2020-12-31 14:01:09,437 | INFO | Packet captured! Waiting 20 seconds...
2020-12-31 14:01:29,456 | INFO | Starting sniffing...

**Comment by pilot1981** [comment]
Hi,
I answer myself to help future readers...I ask owner of this repository to update also wiki @danimtb 

Amazon decided to brick all Amazon dash button suing update via OTA. so you have to do these steps:
1. block access to internet (Amazon OTA server)
2. if button is blocked you can try to rescue it using this procedure: https://blog.christophermullins.com/2019/12/20/rescue-your-amazon-dash-buttons/
3. in sare case, Amazon fixed bug and rescue procedure don't work: you can try to fine new way to rescue it or put it in the trash...
