### ISSUE TITLE
DateTime problem again 

### ISSUE THREAD

**Issue by dustardly** [danimtb/dasshio#79]
same before

hassio 0.91.3 
dasshio 0.3.3

2019-04-15 17:05:16,891 | INFO | Starting sniffing...
2019-04-15 17:05:18,415 | ERROR | Caught exception in sniff: module 'datetime' has no attribute 'utcnow'
Traceback (most recent call last):
  File "/dasshio.py", line 172, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 889, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 32, in arp_display
    current_time = datetime.utcnow()
AttributeError: module 'datetime' has no attribute 'utcnow'
2019-04-15 17:05:18,431 | INFO | Finishing sniffing
2019-04-15 17:05:18,432 | INFO | Starting sniffing...
2019-04-15 17:05:18,562 | ERROR | Caught exception in sniff: module 'datetime' has no attribute 'utcnow'
Traceback (most recent call last):

**Comment by lubeda** [comment]
Same here, even after reinstall of the addon. I am on an x86
Dashio  0.3.3
Home Assistant 0.91.3

**Comment by danimtb** [comment]
ok, I think the import was wrong again. I have to implement some tests... Thanks for reporting

**Comment by danimtb** [comment]
Fixed in https://github.com/danimtb/dasshio/commit/a65b871e9b7c83a2a7723a6f82c2d208030b409d
