### ISSUE TITLE
"repository name must be lowercase"

### ISSUE THREAD

**Issue by charstring1** [danimtb/dasshio#8]
I'm unable to install Dasshio on the latest Hassio release. Here's the error from the supervisor logs: 

```17-09-28 04:34:02 INFO (SyncWorker_15) [hassio.dock.addon] Start build 62cc289b/armhf-addon-dasshio:0.0.7
17-09-28 04:34:04 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/api/addons.py", line 169, in install
    addon.install(version=version), loop=self.loop)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 437, in install
    if not await self.docker.install(version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 184, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 197, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: invalid reference format: repository name must be lowercase```



Any idea what's going on?

**Comment by danimtb** [comment]
Hi @charstring1 and thank you for your report!

I think dasshio is still not compatible with newest version of supervisor.
Could you indicate me the version of your Supervisor and HostOS?

Thanks

**Comment by charstring1** [comment]
I'm using supervisor 0.64 and host OS 1.1. Both are latest I think. :-(

**Comment by danimtb** [comment]
Hi @charstring1 

I have just updated Dasshio to v0.0.8. Now it should work with Hass.io 0.64 and Host OS 1.1

Check: https://github.com/danimtb/dasshio/releases/tag/v0.0.8

Could you give it a try?

**Comment by charstring1** [comment]
Yup, that worked! Just installed and started it.

**Comment by charstring1** [comment]
Thought I could attach an image but I guess not. It works great though, thanks so much for the quick turnaround!

**Comment by danimtb** [comment]
thanks to you too! :D
