### ISSUE TITLE
Error in  sendrecv in  0.3.4

### ISSUE THREAD

**Issue by lubeda** [danimtb/dasshio#81]
2019-04-15 18:27:19,189 | INFO | Reading config file: /data/options.json
2019-04-15 18:27:19,190 | INFO | Starting...
2019-04-15 18:27:19,190 | INFO | Starting sniffing...
2019-04-15 18:36:19,051 | ERROR | Caught exception in sniff: '6c:56:97:9b:52:aa'
Traceback (most recent call last):
  File "/dasshio.py", line 172, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 889, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 44, in arp_display
    last_pressed = timeout_guard[button_address]
KeyError: '6c:56:97:9b:52:aa'
2019-04-15 18:36:19,075 | INFO | Finishing sniffing
2019-04-15 18:36:19,076 | INFO | Starting sniffing...

**Comment by dustardly** [comment]
same

2019-04-15 18:43:13,814 | INFO | Reading config file: /data/options.json
2019-04-15 18:43:13,818 | INFO | Starting...
2019-04-15 18:43:13,818 | INFO | Starting sniffing...
2019-04-15 18:55:52,536 | ERROR | Caught exception in sniff: '34:d2:70:22:1e:a3'
Traceback (most recent call last):
  File "/dasshio.py", line 172, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 889, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 44, in arp_display
    last_pressed = timeout_guard[button_address]
KeyError: '34:d2:70:22:1e:a3'
2019-04-15 18:55:52,561 | INFO | Finishing sniffing
2019-04-15 18:55:52,563 | INFO | Starting sniffing...
2019-04-15 18:55:52,972 | ERROR | Caught exception in sniff: '34:d2:70:22:1e:a3'
Traceback (most recent call last):
  File "/dasshio.py", line 172, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 889, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 44, in arp_display
    last_pressed = timeout_guard[button_address]

**Comment by danimtb** [comment]
Will have to investigate it further. Thanks for reporting

**Comment by dustardly** [comment]
possible have 0.3.1 the last version working on download in meanwhile

**Comment by crispwake** [comment]
Same error, dasshio 0.3.4, hassio 0.91.3.  On 0.3.2 before updating to 0.3.4 was getting an issue with something about function utcnow on datetime doesn't exist (sorry don't have the exact error anymore).

**Comment by Lawrencezarb** [comment]
I think the datetime error is what I am getting now, it was working before. I was on 0.3.1, now on 0.3.2 i get the error, even when I roll back to 0.3.1:

2019-04-15 19:17:58,512 | INFO | Starting sniffing...
2019-04-15 19:17:58,667 | ERROR | Caught exception in sniff: module 'datetime' has no attribute 'utcnow'
Traceback (most recent call last):
  File "/dasshio.py", line 172, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 889, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 32, in arp_display
    current_time = datetime.utcnow()
AttributeError: module 'datetime' has no attribute 'utcnow'
2019-04-15 19:17:58,687 | INFO | Finishing sniffing

**Comment by gdreelin** [comment]
I am getting the same error too and it is beating up my eth0 going in and out of promiscuous mode over and over on 0.3.2. In HASSIO it is not showing upgrades to 0.3.4 at all.

**Comment by danimtb** [comment]
Should be fixed in 0.3.5 and available when travis job ends: https://travis-ci.org/danimtb/dasshio/builds/520446863

Thanks for reporting and sorry for trouble
