### ISSUE TITLE
dasshio lot errors in log

### ISSUE THREAD

**Issue by dustardly** [danimtb/dasshio#83]
I tested now dasshio 0.3.5 HA 0.91.3

this my config:

{
  "timeout": 20,
  "buttons": [
   {
      "name": "nobo",
      "address": "34:D2:70:22:1E:A3",
      "domain": "switch",
      "service": "turn_on",
      "service_data": "{\"entity_id\": \"switch.cancello\"}"
    }
  ]
}

THIS THE LOG

2019-04-15 22:27:31,618 | INFO | Reading config file: /data/options.json
2019-04-15 22:27:31,622 | INFO | Starting...
2019-04-15 22:27:31,623 | INFO | Starting sniffing...
2019-04-15 22:28:07,766 | INFO | nobo button pressed!
2019-04-15 22:28:09,004 | ERROR | Unable to perform  request: Check [url], [body], [headers] and API password or                     [domain], [service] and [service_data] format.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='hassio', port=80): Read timed out. (read timeout=0.5)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/dasshio.py", line 67, in arp_display
    timeout=request_timeout_secs
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='hassio', port=80): Read timed out. (read timeout=0.5)
2019-04-15 22:28:09,028 | INFO | Finishing sniffing
2019-04-15 22:28:09,029 | INFO | Starting sniffing...

**Comment by LucaBopf** [comment]
Also a lot of errors here
I use dasshio 0.3.3 HA 0.91.3


LOG:
2019-04-15 22:45:19,025 | INFO | Finishing sniffing
2019-04-15 22:45:19,027 | INFO | Starting sniffing...
2019-04-15 22:45:20,013 | ERROR | Caught exception in sniff: module 'datetime' has no attribute 'utcnow'
Traceback (most recent call last):
  File "/dasshio.py", line 172, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 889, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 32, in arp_display
    current_time = datetime.utcnow()
AttributeError: module 'datetime' has no attribute 'utcnow'
2019-04-15 22:45:20,175 | INFO | Finishing sniffing
2019-04-15 22:45:20,176 | INFO | Starting sniffing...
2019-04-15 22:45:21,053 | ERROR | Caught exception in sniff: module 'datetime' has no attribute 'utcnow'
Traceback (most recent call last):
  File "/dasshio.py", line 172, in <module>
    count=0)
  File "/usr/lib/python3.6/site-packages/scapy/sendrecv.py", line 889, in sniff
    if stop_filter and stop_filter(p):
  File "/dasshio.py", line 32, in arp_display
    current_time = datetime.utcnow()
AttributeError: module 'datetime' has no attribute 'utcnow'
2019-04-15 22:45:21,095 | INFO | Finishing sniffing
2019-04-15 22:45:21,096 | INFO | Starting sniffing...

**Comment by danimtb** [comment]
Ok, seems there is an error in the timeout parameter for requests. Will fix it and release 0.3.6
